static_homepage:
    type:     rest
    name_prefix:  static_
    resource : StaticBundle\Controller\DefaultController
#    path: /
#    defaults: { _controller: StaticBundle:Default:index }

business_bundle:
    type: rest
    prefix:  /business
    name_prefix:  static_business
    resource: StaticBundle\Controller\BusinessController

client_bundle:
    type: rest
    prefix:  /client
    name_prefix:  static_client
    resource: StaticBundle\Controller\ClientController

#post_demo_chat:
#    path:  /chat
#    defaults: { _controller: StaticBundle:Chat:postMessage, _format: ~ }
#
#get_demo_chat:
#    path:  /chat
#    defaults: { _controller: StaticBundle:Chat:getMessage, _format: ~ }

