static_homepage:
    type:     rest
    name_prefix:  static_
    resource : StaticBundle\Controller\DefaultController
#    path: /
#    defaults: { _controller: StaticBundle:Default:index }

chat_bundle:
    type: rest
    path:  /chat
    resource: StaticBundle\Controller\ChatController

#post_demo_chat:
#    path:  /chat
#    defaults: { _controller: StaticBundle:Chat:postMessage, _format: ~ }
#
#get_demo_chat:
#    path:  /chat
#    defaults: { _controller: StaticBundle:Chat:getMessage, _format: ~ }

